POST http://localhost:3000/api/verify
Content-Type: application/json

{
  "message": "foo",
  "signature": "0x0"
}

###

GET http://localhost:3000/api/siwe/nonce

###

GET http://localhost:3000/api/sanctions?address=0x76D85B4C0Fc497EeCc38902397aC608000A06607

###

POST {{$dotenv AIRTABLE_ENDPOINT_URL}}
Authorization: Bearer {{$dotenv AIRTABLE_TOKEN}}
Content-Type: application/json

{
    "fields": {
      "InquiryId": "inq_abcde",
      "CryptoWallet": "0xabcd",
      "Country": "DE",
      "EMail": "moo@loo.boo",
      "Referrer": "foo"
    }
  }

###

POST http://localhost:3000/api/webhook
Content-Type: application/json

< samples/persona.json

### Graphql

POST 
Host: subgraph.satsuma-prod.com
Origin: https://juicebox.money

query Participant($projectId: Int,$address: Bytes) {
  participants(where: {projectId: $projectId,address: $address}) {
    project {
        id
      }
      projectId
      address
      volume
      volumeUSD
      balance
      paymentsCount
      stakedBalance
  }
}

{
  "projectId": 698,
  "address": "0x0"
}

###

POST 
Content-Type: application/json
Origin: https://juicebox.money

{
  "query": "query Participant($projectId: Int,$address: Bytes) {  participants(where: {projectId: $projectId,address: $address}) {    project {        id      }      projectId     address      volume  }}",
  "variables": {
    "projectId": 698,
    "address": "0x"
  }
}

###

GET http://localhost:3000/api/jb/?address=